/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author antho6229
 */
public class diceGameForm extends javax.swing.JFrame {

    /**
     * Creates new form diceGameForm
     */
    
    //declare variables
    int numRolls = 0;
    int numCorrect = 0;
    int numIncorrect = 0;
    int guess, roll;
    double perCorrect;
    
    public diceGameForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        instructionLabel = new javax.swing.JLabel();
        yourGuessLabel = new javax.swing.JLabel();
        guessText = new javax.swing.JTextField();
        rollButton = new javax.swing.JButton();
        rollTitleLabel = new javax.swing.JLabel();
        rollLabel = new javax.swing.JLabel();
        numberOfRollsTitleLabel = new javax.swing.JLabel();
        numberOfCorrectGuessesTitleLabel = new javax.swing.JLabel();
        numberOfIncorrectGuessesTitleLabel = new javax.swing.JLabel();
        percentOfCorrectGuessesTitleLabel = new javax.swing.JLabel();
        numRollsLabel = new javax.swing.JLabel();
        numCorrectLabel = new javax.swing.JLabel();
        numIncorrectLabel = new javax.swing.JLabel();
        percentCorrectLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(0, 0, 0));

        titleLabel.setFont(new java.awt.Font("PosterBodoniGreek BT", 0, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 0));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Dice Guessing Game");

        instructionLabel.setFont(new java.awt.Font("PosterBodoniGreek BT", 0, 14)); // NOI18N
        instructionLabel.setForeground(new java.awt.Color(255, 255, 0));
        instructionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instructionLabel.setText("Enter a number form 1 to 6, then roll the dice!");

        yourGuessLabel.setFont(new java.awt.Font("PosterBodoniGreek BT", 0, 12)); // NOI18N
        yourGuessLabel.setForeground(new java.awt.Color(255, 255, 0));
        yourGuessLabel.setText("Your guess:");

        guessText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guessTextActionPerformed(evt);
            }
        });

        rollButton.setFont(new java.awt.Font("PosterBodoniGreek BT", 0, 11)); // NOI18N
        rollButton.setText("Roll Dice");
        rollButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollButtonActionPerformed(evt);
            }
        });

        rollTitleLabel.setFont(new java.awt.Font("PosterBodoniGreek BT", 0, 12)); // NOI18N
        rollTitleLabel.setForeground(new java.awt.Color(255, 255, 0));
        rollTitleLabel.setText("Dice roll:");

        rollLabel.setFont(new java.awt.Font("PosterBodoniGreek BT", 0, 12)); // NOI18N
        rollLabel.setForeground(new java.awt.Color(255, 255, 0));
        rollLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rollLabel.setText("0");

        numberOfRollsTitleLabel.setFont(new java.awt.Font("PosterBodoniGreek BT", 0, 12)); // NOI18N
        numberOfRollsTitleLabel.setForeground(new java.awt.Color(255, 255, 0));
        numberOfRollsTitleLabel.setText("Number of rolls:");

        numberOfCorrectGuessesTitleLabel.setFont(new java.awt.Font("PosterBodoniGreek BT", 0, 12)); // NOI18N
        numberOfCorrectGuessesTitleLabel.setForeground(new java.awt.Color(255, 255, 0));
        numberOfCorrectGuessesTitleLabel.setText("Number of correct guesses:");

        numberOfIncorrectGuessesTitleLabel.setFont(new java.awt.Font("PosterBodoniGreek BT", 0, 12)); // NOI18N
        numberOfIncorrectGuessesTitleLabel.setForeground(new java.awt.Color(255, 255, 0));
        numberOfIncorrectGuessesTitleLabel.setText("Number of incorrect guesses:");

        percentOfCorrectGuessesTitleLabel.setFont(new java.awt.Font("PosterBodoniGreek BT", 0, 12)); // NOI18N
        percentOfCorrectGuessesTitleLabel.setForeground(new java.awt.Color(255, 255, 0));
        percentOfCorrectGuessesTitleLabel.setText("Percent of correct guesses:");

        numRollsLabel.setFont(new java.awt.Font("PosterBodoniGreek BT", 0, 12)); // NOI18N
        numRollsLabel.setForeground(new java.awt.Color(255, 255, 0));
        numRollsLabel.setText("0");

        numCorrectLabel.setFont(new java.awt.Font("PosterBodoniGreek BT", 0, 12)); // NOI18N
        numCorrectLabel.setForeground(new java.awt.Color(255, 255, 0));
        numCorrectLabel.setText("0");

        numIncorrectLabel.setFont(new java.awt.Font("PosterBodoniGreek BT", 0, 12)); // NOI18N
        numIncorrectLabel.setForeground(new java.awt.Color(255, 255, 0));
        numIncorrectLabel.setText("0");

        percentCorrectLabel.setFont(new java.awt.Font("PosterBodoniGreek BT", 0, 12)); // NOI18N
        percentCorrectLabel.setForeground(new java.awt.Color(255, 255, 0));
        percentCorrectLabel.setText("0");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(instructionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(numberOfRollsTitleLabel)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(guessText, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(yourGuessLabel))
                                .addGap(59, 59, 59)
                                .addComponent(rollButton))
                            .addComponent(numberOfCorrectGuessesTitleLabel)
                            .addComponent(numberOfIncorrectGuessesTitleLabel)
                            .addComponent(percentOfCorrectGuessesTitleLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rollLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rollTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numRollsLabel)
                            .addComponent(numCorrectLabel)
                            .addComponent(numIncorrectLabel)
                            .addComponent(percentCorrectLabel))
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instructionLabel)
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yourGuessLabel)
                    .addComponent(rollTitleLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guessText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rollButton)
                    .addComponent(rollLabel))
                .addGap(33, 33, 33)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberOfRollsTitleLabel)
                    .addComponent(numRollsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberOfCorrectGuessesTitleLabel)
                    .addComponent(numCorrectLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberOfIncorrectGuessesTitleLabel)
                    .addComponent(numIncorrectLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(percentOfCorrectGuessesTitleLabel)
                    .addComponent(percentCorrectLabel))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guessTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guessTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guessTextActionPerformed

    private void rollButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollButtonActionPerformed
        roll = (int)Math.round(Math.random()*5+1);
        guess = Integer.parseInt(guessText.getText());
        
        numRolls++;
        
        rollLabel.setText("" + roll);
        
        if(guess==roll){
            numCorrect++;
        }else{
            numIncorrect++;
        }
        
        perCorrect = ((double)numCorrect/(double)numRolls) * 100;
        perCorrect = (Math.round(perCorrect)*100)/100;
        
        numRollsLabel.setText("" + numRolls);
        numCorrectLabel.setText("" + numCorrect);
        numIncorrectLabel.setText("" + numIncorrect);
        percentCorrectLabel.setText("" + perCorrect + "%");
        
        
        
    }//GEN-LAST:event_rollButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(diceGameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(diceGameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(diceGameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(diceGameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new diceGameForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField guessText;
    private javax.swing.JLabel instructionLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel numCorrectLabel;
    private javax.swing.JLabel numIncorrectLabel;
    private javax.swing.JLabel numRollsLabel;
    private javax.swing.JLabel numberOfCorrectGuessesTitleLabel;
    private javax.swing.JLabel numberOfIncorrectGuessesTitleLabel;
    private javax.swing.JLabel numberOfRollsTitleLabel;
    private javax.swing.JLabel percentCorrectLabel;
    private javax.swing.JLabel percentOfCorrectGuessesTitleLabel;
    private javax.swing.JButton rollButton;
    private javax.swing.JLabel rollLabel;
    private javax.swing.JLabel rollTitleLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel yourGuessLabel;
    // End of variables declaration//GEN-END:variables
}
